name: BukkitToken
main: com.arkflame.bukkittoken.BukkitToken
version: 0.0.1
author: ArkFlame
api: "1.13"
api-version: "1.13"
softdepend: [HamsterAPI]
commands:
  token:
    description: "Generates a token for web registration"